{{define "config-frontend"}}
server {
   listen 80;
   listen [::]:80;
   server_name localhost;
   location / {
     root /usr/share/nginx/html;
     index  index.html index.htm;
     # try_files $uri $uri/index.html =404;
     try_files $uri $uri/ /index.html;
   }

   location /login {
     root /usr/share/nginx/html;
     index  index.html index.htm;
     try_files $uri $uri/index.html =404;
     # try_files $uri $uri/ /index.html;
   }

   location ^~ /api/ {
     # proxy_pass [proxy_pass 할 주소];
     proxy_pass "{{ tpl .Values.mainApiServerEndpoint . }}";
     proxy_http_version 1.1;
     proxy_set_header Host $http_host;
     proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_connect_timeout 3600;
     proxy_send_timeout 3600;
     proxy_read_timeout 3600;
   }

   location /openapi/ {
     # proxy_pass [proxy_pass 할 주소];
     proxy_pass "{{ tpl .Values.mainApiServerEndpoint . }}";
     proxy_http_version 1.1;
     proxy_set_header Host $http_host;
     proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_connect_timeout 3600;
     proxy_send_timeout 3600;
     proxy_read_timeout 3600;
   }
}
{{end}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
data:
  default.conf: {{ (include "config-frontend" .) | trim | quote }} 
