apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-logstash-inference-log-input
  namespace: {{ .Release.Namespace }}
spec: 
  ports: 
  - name: "8080"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: logstash
